name: frontend_app
description: "A new Flutter project for Real-time Speech-to-Speech Translation."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0   # सर्वर से लाइव जुड़ने के लिए
  permission_handler: ^11.3.1  # माइक की परमिशन लेने के लिए

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
