name: marketplace_app
description: Multi-role Marketplace App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.7.0
  provider: ^6.0.5
  url_launcher: ^6.2.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
