platform :ios, '12.0'
use_frameworks!
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Flutter', :path => '../.symlinks/flutter/ios'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    end
  end
end