name: Build and Test Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Backend Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'

    - name: Get Flutter Packages
      run: |
        cd frontend_app
        flutter pub get

    - name: Build Flutter Web/App
      run: |
        cd frontend_app
        flutter build appbundle --release || flutter build apk --release
